definitions:
  entity.Product:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: string
      image:
        type: string
      rating:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a products server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Products API
  version: "1.0"
paths:
  /products:
    get:
      consumes:
      - '*/*'
      description: get List Product
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Product'
      summary: List Product
      tags:
      - products
    post:
      consumes:
      - '*/*'
      description: Post Create Product
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Product'
      summary: Create Product
      tags:
      - products
  /products/{id}:
    delete:
      consumes:
      - application/json
      description: get Delete Product
      produces:
      - application/json
      summary: Delete Product
      tags:
      - products
    get:
      consumes:
      - application/json
      description: get Detail Product
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Product'
      summary: Detail Product
      tags:
      - products
    put:
      consumes:
      - application/json
      description: get Update Product
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Product'
      summary: Update Product
      tags:
      - products
schemes:
- http
swagger: "2.0"
