# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: opticdev/optic-changelog@7f5cd6a3fadde150fc144261b803bfa1beba3ebd
        with:
          GITHUB_TOKEN: ${{secrets.OPTIC_GITHUB_TOKEN}}
          OPTIC_API_KEY: ${{secrets.OPTIC_API_KEY}}
